
django.request: 2025-02-13 09:14:44,244 - WARNING - Not Found: /api/
apis.views: 2025-02-13 09:14:49,606 - INFO - This is an info log
apis.views: 2025-02-13 09:14:49,610 - ERROR - Employee with id 8 does not exist
django.utils.autoreload: 2025-02-13 09:36:43,405 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-13 09:36:45,980 - WARNING - Not Found: /
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 09:40:56,887 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020EE00B4A80>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 09:41:30,811 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020EE00277C0>.
django.utils.autoreload: 2025-02-13 10:27:28,700 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-13 10:27:31,528 - WARNING - Not Found: /
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:27:53,277 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA4351040>.
MARKDOWN: 2025-02-13 10:27:53,454 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-13 10:27:53,454 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:30:36,573 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA46E7580>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:32:57,500 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA47A9080>.
django.request: 2025-02-13 10:32:57,504 - WARNING - Method Not Allowed: /api/validateUser/
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:33:45,280 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA4633280>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:34:05,122 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA4672480>.
django.request: 2025-02-13 10:34:05,131 - WARNING - Not Found: /api/validateUser/
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:38:03,881 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA48921C0>.
django.request: 2025-02-13 10:47:23,578 - WARNING - Not Found: /api/
django.utils.autoreload: 2025-02-13 11:51:25,882 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 11:51:28,465 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 11:51:43,350 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001DB2D617AC0>.
django.utils.autoreload: 2025-02-13 11:57:21,907 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\serializers.py changed, reloading.
django.utils.autoreload: 2025-02-13 11:57:23,045 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 12:08:30,924 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:08:32,239 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 12:15:08,106 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\serializers.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:15:10,998 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 12:18:03,644 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:18:06,494 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:18:13,260 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FCEEBFC0>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:18:14,545 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FD141D40>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:18:20,356 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FD2CF780>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:20:36,807 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FD3E6D00>.
django.request: 2025-02-13 12:20:36,971 - ERROR - Internal Server Error: /api/userWishlist/prefetch_related/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Django Training SK\Django\DjangoLearning\apis\views.py", line 106, in get
    wishlistSerializer = UserWishlistSerializer(user.wishlist.all(), many="True").data
NameError: name 'UserWishlistSerializer' is not defined
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:20:47,062 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FD2A27C0>.
django.request: 2025-02-13 12:20:47,140 - ERROR - Internal Server Error: /api/userWishlist/prefetch_related/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Django Training SK\Django\DjangoLearning\apis\views.py", line 106, in get
    wishlistSerializer = UserWishlistSerializer(user.wishlist.all(), many="True").data
NameError: name 'UserWishlistSerializer' is not defined
django.utils.autoreload: 2025-02-13 12:21:17,124 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\serializers.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:21:18,813 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 12:21:29,998 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:21:31,602 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:21:36,321 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020737833C40>.
django.utils.autoreload: 2025-02-13 12:22:23,137 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:22:24,923 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:22:33,810 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000026FDAF4A040>.
