
django.request: 2025-02-13 09:14:44,244 - WARNING - Not Found: /api/
apis.views: 2025-02-13 09:14:49,606 - INFO - This is an info log
apis.views: 2025-02-13 09:14:49,610 - ERROR - Employee with id 8 does not exist
django.utils.autoreload: 2025-02-13 09:36:43,405 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-13 09:36:45,980 - WARNING - Not Found: /
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 09:40:56,887 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020EE00B4A80>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 09:41:30,811 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020EE00277C0>.
django.utils.autoreload: 2025-02-13 10:27:28,700 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-13 10:27:31,528 - WARNING - Not Found: /
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:27:53,277 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA4351040>.
MARKDOWN: 2025-02-13 10:27:53,454 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-13 10:27:53,454 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:30:36,573 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA46E7580>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:32:57,500 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA47A9080>.
django.request: 2025-02-13 10:32:57,504 - WARNING - Method Not Allowed: /api/validateUser/
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:33:45,280 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA4633280>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:34:05,122 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA4672480>.
django.request: 2025-02-13 10:34:05,131 - WARNING - Not Found: /api/validateUser/
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 10:38:03,881 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001CFA48921C0>.
django.request: 2025-02-13 10:47:23,578 - WARNING - Not Found: /api/
django.utils.autoreload: 2025-02-13 11:51:25,882 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 11:51:28,465 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 11:51:43,350 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001DB2D617AC0>.
django.utils.autoreload: 2025-02-13 11:57:21,907 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\serializers.py changed, reloading.
django.utils.autoreload: 2025-02-13 11:57:23,045 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 12:08:30,924 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:08:32,239 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 12:15:08,106 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\serializers.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:15:10,998 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 12:18:03,644 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:18:06,494 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:18:13,260 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FCEEBFC0>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:18:14,545 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FD141D40>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:18:20,356 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FD2CF780>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:20:36,807 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FD3E6D00>.
django.request: 2025-02-13 12:20:36,971 - ERROR - Internal Server Error: /api/userWishlist/prefetch_related/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Django Training SK\Django\DjangoLearning\apis\views.py", line 106, in get
    wishlistSerializer = UserWishlistSerializer(user.wishlist.all(), many="True").data
NameError: name 'UserWishlistSerializer' is not defined
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:20:47,062 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C6FD2A27C0>.
django.request: 2025-02-13 12:20:47,140 - ERROR - Internal Server Error: /api/userWishlist/prefetch_related/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Django Training SK\Django\DjangoLearning\apis\views.py", line 106, in get
    wishlistSerializer = UserWishlistSerializer(user.wishlist.all(), many="True").data
NameError: name 'UserWishlistSerializer' is not defined
django.utils.autoreload: 2025-02-13 12:21:17,124 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\serializers.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:21:18,813 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 12:21:29,998 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:21:31,602 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:21:36,321 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020737833C40>.
django.utils.autoreload: 2025-02-13 12:22:23,137 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 12:22:24,923 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 12:22:33,810 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000026FDAF4A040>.
django.utils.autoreload: 2025-02-13 13:21:07,099 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 15:08:45,191 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-13 15:10:33,282 - WARNING - Not Found: /
django.request: 2025-02-13 15:10:33,336 - WARNING - Not Found: /favicon.ico
django.request: 2025-02-13 15:12:09,207 - WARNING - Not Found: /
django.utils.autoreload: 2025-02-13 15:32:27,288 - INFO - H:\Learnings\Securekloud Learnings\Django\djangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 15:32:28,374 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 15:38:49,931 - INFO - H:\Learnings\Securekloud Learnings\Django\djangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-13 15:38:51,345 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-13 15:39:01,015 - WARNING - Not Found: /users
django.request: 2025-02-13 15:39:13,277 - WARNING - Not Found: /api/users
django.utils.autoreload: 2025-02-13 15:42:22,843 - INFO - H:\Learnings\Securekloud Learnings\Django\djangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-13 15:42:24,067 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 15:42:37,867 - INFO - H:\Learnings\Securekloud Learnings\Django\djangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-13 15:42:38,864 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 15:42:40,978 - INFO - H:\Learnings\Securekloud Learnings\Django\djangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-13 15:42:42,138 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:42:46,216 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x00000241B999DB80>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:43:09,845 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x00000241B9947E80>.
django.utils.autoreload: 2025-02-13 15:43:49,742 - INFO - H:\Learnings\Securekloud Learnings\Django\djangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-13 15:43:50,931 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-13 15:45:07,756 - INFO - H:\Learnings\Securekloud Learnings\Django\djangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-13 15:45:08,758 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:45:22,117 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002547A9E81C0>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:45:29,863 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002547AA03300>.
django.request: 2025-02-13 15:45:45,407 - WARNING - Not Found: /api/user/1/
django.request: 2025-02-13 15:45:51,526 - WARNING - Not Found: /api/user/
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:45:57,821 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002547A94F000>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:46:00,553 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002547A9988C0>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:46:07,001 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002547A93AD40>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:46:12,753 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002547A5B8580>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:48:29,158 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002547A9B1B40>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-13 15:48:52,560 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002547A93B040>.
django.utils.autoreload: 2025-02-13 15:49:13,119 - INFO - H:\Learnings\Securekloud Learnings\Django\djangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-13 15:49:14,286 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:20:45,045 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-14 10:20:54,456 - WARNING - Not Found: /
django.request: 2025-02-14 10:20:55,424 - WARNING - Not Found: /favicon.ico
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:21:03,722 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002BA92E78D80>.
MARKDOWN: 2025-02-14 10:21:03,835 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:21:03,837 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:21:20,333 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002BA93445DC0>.
MARKDOWN: 2025-02-14 10:21:20,336 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:21:20,337 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:21:25,043 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002BA933AAD40>.
MARKDOWN: 2025-02-14 10:21:25,047 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:21:25,049 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.request: 2025-02-14 10:21:28,722 - WARNING - Not Found: /
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:21:38,643 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002BA93333F40>.
MARKDOWN: 2025-02-14 10:21:38,645 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:21:38,647 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:21:43,321 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002BA93167880>.
MARKDOWN: 2025-02-14 10:21:43,326 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:21:43,327 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:21:48,002 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002BA9335A540>.
MARKDOWN: 2025-02-14 10:21:48,011 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:21:48,012 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:21:53,777 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002BA933721C0>.
MARKDOWN: 2025-02-14 10:21:53,783 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:21:53,783 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:22:09,579 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002BA9336FC80>.
MARKDOWN: 2025-02-14 10:22:09,588 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:22:09,588 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:22:16,285 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002BA933BBF00>.
MARKDOWN: 2025-02-14 10:22:16,302 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:22:16,303 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.utils.autoreload: 2025-02-14 10:22:41,044 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:22:43,621 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:23:09,573 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:23:12,225 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:23:22,082 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:23:24,274 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:23:51,665 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:23:54,044 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-14 10:23:57,830 - WARNING - Not Found: /
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:24:01,633 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000021E03565680>.
MARKDOWN: 2025-02-14 10:24:01,813 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:24:01,813 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:24:04,119 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000021E0365EE00>.
MARKDOWN: 2025-02-14 10:24:04,149 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:24:04,149 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.utils.autoreload: 2025-02-14 10:24:58,165 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:25:00,816 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:25:56,932 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:25:59,853 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:29:58,604 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\serializers.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:30:01,579 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:30:56,344 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:30:58,822 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:31:10,344 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001EC9A584E00>.
MARKDOWN: 2025-02-14 10:31:10,485 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:31:10,487 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:34:41,858 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001EC9A57DCC0>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:34:42,772 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001EC9A521C00>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:35:02,386 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001EC9A6FBE00>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:35:12,253 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001EC9A717100>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:35:24,472 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001EC9A77FE40>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:36:38,431 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001EC9A886D80>.
django.utils.autoreload: 2025-02-14 10:36:54,864 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:36:58,311 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:37:19,457 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:37:21,770 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:37:23,122 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000022975BA8040>.
django.utils.autoreload: 2025-02-14 10:37:56,874 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:37:59,584 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:38:04,552 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000027749B0AA40>.
MARKDOWN: 2025-02-14 10:38:04,834 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:38:04,834 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:38:07,889 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000027749F80040>.
django.request: 2025-02-14 10:38:07,993 - ERROR - Internal Server Error: /api/users-with-wishlist/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: UserWithWishlistViewSet.list() takes 1 positional argument but 2 were given
django.utils.autoreload: 2025-02-14 10:38:17,802 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:38:20,293 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:38:21,267 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000021E02A512C0>.
MARKDOWN: 2025-02-14 10:38:21,364 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:38:21,366 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:38:51,099 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000021E02F57040>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:40:48,464 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000021E02B9B340>.
django.utils.autoreload: 2025-02-14 10:45:19,632 - INFO - E:\Django Training SK\Django\DjangoLearning\products\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:45:21,922 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:45:50,056 - INFO - E:\Django Training SK\Django\DjangoLearning\products\urls.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:45:52,637 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-14 10:45:56,250 - WARNING - Not Found: /
django.request: 2025-02-14 10:46:07,870 - WARNING - Not Found: /product/
django.request: 2025-02-14 10:46:18,667 - ERROR - Internal Server Error: /product/sample/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: APIView.as_view() takes 1 positional argument but 2 were given
django.utils.autoreload: 2025-02-14 10:46:32,793 - INFO - E:\Django Training SK\Django\DjangoLearning\products\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:46:35,043 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-14 10:46:36,177 - ERROR - Internal Server Error: /product/sample/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: APIView.as_view() takes 1 positional argument but 2 were given
django.utils.autoreload: 2025-02-14 10:46:51,775 - INFO - E:\Django Training SK\Django\DjangoLearning\products\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:46:54,120 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-14 10:46:57,020 - ERROR - Internal Server Error: /product/sample/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: APIView.as_view() takes 1 positional argument but 2 were given
django.utils.autoreload: 2025-02-14 10:47:37,496 - INFO - E:\Django Training SK\Django\DjangoLearning\products\urls.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:47:39,959 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:47:41,355 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020BAE39EB80>.
django.request: 2025-02-14 10:47:42,171 - ERROR - Internal Server Error: /product/sample/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 979, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\_auth.py", line 268, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\_auth.py", line 121, in _roundtrip
    pkt = conn._read_packet()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Django Training SK\Django\DjangoLearning\products\views.py", line 19, in get
    print("Products:", product_serializer.data)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 979, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\_auth.py", line 268, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\_auth.py", line 121, in _roundtrip
    pkt = conn._read_packet()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
django.utils.autoreload: 2025-02-14 10:50:56,205 - INFO - E:\Django Training SK\Django\DjangoLearning\djangoLearning\settings.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:50:59,039 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-14 10:51:32,582 - INFO - E:\Django Training SK\Django\DjangoLearning\products\migrations\0001_initial.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:51:35,777 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:52:36,742 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000023994A51080>.
MARKDOWN: 2025-02-14 10:52:37,866 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:52:37,867 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:52:50,648 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x00000239949A3040>.
MARKDOWN: 2025-02-14 10:52:50,650 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:52:50,651 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:53:56,223 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002399489ED00>.
MARKDOWN: 2025-02-14 10:53:56,241 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-14 10:53:56,242 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:54:53,509 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000023994965340>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-14 10:55:18,576 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000023994D90680>.
django.utils.autoreload: 2025-02-14 10:55:54,844 - INFO - E:\Django Training SK\Django\DjangoLearning\products\views.py changed, reloading.
django.utils.autoreload: 2025-02-14 10:55:57,837 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-17 07:58:49,270 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-17 07:59:05,103 - WARNING - Not Found: /
django.request: 2025-02-17 07:59:06,605 - WARNING - Not Found: /favicon.ico
django.request: 2025-02-17 07:59:22,896 - WARNING - Not Found: /product/
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 07:59:29,697 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x00000216787D3C00>.
MARKDOWN: 2025-02-17 07:59:30,381 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 07:59:30,389 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.utils.autoreload: 2025-02-17 08:02:13,926 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:02:16,894 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-17 08:03:17,496 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:03:19,725 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-17 08:03:27,495 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:03:29,474 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-17 08:07:38,320 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:07:43,331 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000018A687DC580>.
MARKDOWN: 2025-02-17 08:07:43,464 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 08:07:43,464 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.request: 2025-02-17 08:08:05,516 - WARNING - Not Found: /asm
django.request: 2025-02-17 08:15:07,399 - WARNING - Not Found: /apis/
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:15:13,875 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000018A68F58900>.
MARKDOWN: 2025-02-17 08:15:13,879 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 08:15:13,879 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:15:18,537 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000018A68B9C7C0>.
MARKDOWN: 2025-02-17 08:15:18,549 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 08:15:18,549 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:15:41,900 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000018A69093100>.
django.request: 2025-02-17 08:15:42,031 - ERROR - Internal Server Error: /api/users-with-wishlist/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Django Training SK\Django\DjangoLearning\apis\views.py", line 271, in list
    "users": serializer.data
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "E:\Django Training SK\Django\DjangoLearning\apis\serializers.py", line 23, in get_wishlist
    return [
  File "E:\Django Training SK\Django\DjangoLearning\apis\serializers.py", line 26, in <listcomp>
    "productName": item.productName,
AttributeError: 'UserWishlist' object has no attribute 'productName'
django.utils.autoreload: 2025-02-17 08:16:54,533 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\serializers.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:16:58,078 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:17:00,343 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C5B58FA1C0>.
MARKDOWN: 2025-02-17 08:17:00,460 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 08:17:00,461 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:17:40,712 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C5B59E5A00>.
MARKDOWN: 2025-02-17 08:17:40,729 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 08:17:40,730 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:18:52,621 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C5B5CAD6C0>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:19:01,279 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C5B5C98E40>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:19:07,554 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C5B5C41480>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:19:14,373 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001C5B5CAC8C0>.
django.utils.autoreload: 2025-02-17 08:31:24,080 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:31:28,673 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:31:32,896 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001F79F7CBDC0>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:32:15,501 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001F79FCE2340>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:32:20,490 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001F79F9D0BC0>.
django.utils.autoreload: 2025-02-17 08:33:13,955 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:33:18,097 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:33:20,068 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002707835E440>.
django.utils.autoreload: 2025-02-17 08:33:46,418 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:33:49,368 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:33:57,545 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001D32E8237C0>.
django.utils.autoreload: 2025-02-17 08:34:11,151 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:34:14,155 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:34:18,058 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020BE80749C0>.
django.utils.autoreload: 2025-02-17 08:38:30,910 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:38:34,014 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:38:39,279 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020876AD1FC0>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 08:42:17,180 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000020876918040>.
MARKDOWN: 2025-02-17 08:42:17,430 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 08:42:17,431 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.utils.autoreload: 2025-02-17 08:46:59,694 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\views.py changed, reloading.
django.utils.autoreload: 2025-02-17 08:47:02,609 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-17 08:57:36,415 - WARNING - Not Found: /api/translationDemo/fr/
django.request: 2025-02-17 09:04:16,562 - WARNING - Not Found: /api/fr
django.request: 2025-02-17 09:04:20,505 - WARNING - Not Found: /api/fr/
django.utils.autoreload: 2025-02-17 09:09:20,355 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:09:24,736 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:09:32,038 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001F47417A380>.
django.request: 2025-02-17 09:09:32,293 - ERROR - Internal Server Error: /api/userWishlist/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: apis_userwishlist._order

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Django Training SK\Django\DjangoLearning\apis\views.py", line 94, in get
    "count": len(serializer.data),  # Count of users
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "E:\Django Training SK\Django\DjangoLearning\apis\serializers.py", line 23, in get_wishlist
    return [
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: apis_userwishlist._order
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:09:44,266 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001F47424AF40>.
django.request: 2025-02-17 09:09:44,410 - ERROR - Internal Server Error: /api/userWishlist/
Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: apis_userwishlist._order

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Django Training SK\Django\DjangoLearning\apis\views.py", line 94, in get
    "count": len(serializer.data),  # Count of users
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "E:\Django Training SK\Django\DjangoLearning\apis\serializers.py", line 23, in get_wishlist
    return [
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Hari Prasad\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: apis_userwishlist._order
django.utils.autoreload: 2025-02-17 09:10:24,748 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\models.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:10:28,254 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:10:34,616 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000019069BC0A80>.
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:10:56,185 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x0000019069BF7680>.
django.utils.autoreload: 2025-02-17 09:17:37,388 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:17:41,365 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:17:50,660 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001AE88E95B80>.
MARKDOWN: 2025-02-17 09:17:50,949 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 09:17:50,951 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:17:55,509 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001AE88D1BE80>.
MARKDOWN: 2025-02-17 09:17:55,514 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 09:17:55,516 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.utils.autoreload: 2025-02-17 09:18:02,374 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:18:05,418 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-17 09:18:10,985 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:18:14,179 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:18:18,612 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001D1E3DFCAC0>.
MARKDOWN: 2025-02-17 09:18:18,730 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 09:18:18,731 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.utils.autoreload: 2025-02-17 09:19:03,765 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:19:07,210 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:19:11,710 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001EA829C67C0>.
MARKDOWN: 2025-02-17 09:19:11,832 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 09:19:11,832 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:19:15,529 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000001EA82AABA40>.
MARKDOWN: 2025-02-17 09:19:15,531 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 09:19:15,532 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.utils.autoreload: 2025-02-17 09:19:23,898 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:19:27,289 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-17 09:19:54,536 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:19:59,045 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-17 09:20:06,432 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:20:09,498 - INFO - Watching for file changes with StatReloader
django.utils.autoreload: 2025-02-17 09:21:19,738 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:21:22,825 - INFO - Watching for file changes with StatReloader
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:21:41,209 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x000002041649CD00>.
MARKDOWN: 2025-02-17 09:21:41,389 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 09:21:41,391 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.utils.autoreload: 2025-02-17 09:21:58,123 - INFO - E:\Django Training SK\Django\DjangoLearning\apis\urls.py changed, reloading.
django.utils.autoreload: 2025-02-17 09:22:01,452 - INFO - Watching for file changes with StatReloader
django.request: 2025-02-17 09:22:02,701 - WARNING - Not Found: /api/
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:22:09,489 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x00000109E6B86880>.
MARKDOWN: 2025-02-17 09:22:09,626 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 09:22:09,627 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:22:15,955 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x00000109E727EAC0>.
MARKDOWN: 2025-02-17 09:22:15,978 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 09:22:15,981 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
oauthlib.oauth2.rfc6749.endpoints.resource: 2025-02-17 09:22:18,195 - DEBUG - Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x00000109E7071AC0>.
MARKDOWN: 2025-02-17 09:22:18,230 - DEBUG - Successfully imported extension module "markdown.extensions.toc".
MARKDOWN: 2025-02-17 09:22:18,231 - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
django.utils.autoreload: 2025-02-17 11:30:05,898 - INFO - Watching for file changes with StatReloader
